export const SET_CURRENCIES = "SET_COUNTRIES";
export const SET_QUOTES = "SET_QUOTES";
export const SET_FIRST_CURRENCY = "SET_FIRST_CURRENCY";
export const SET_SECOND_CURRENCY = "SET_SECOND_CURRENCY";
export const SET_FIRST_AMOUNT = "SET_FIRST_AMOUNT";
export const SET_SECOND_AMOUNT = "SET_SECOND_AMOUNT";
